# Generated by Django 5.1.4 on 2024-12-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('task', 'file_name')},
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('user', 'message')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('project', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'user')},
        ),
    ]
