# Generated by Django 5.1.4 on 2024-12-29 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('projects', '0003_alter_project_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectreport',
            options={'ordering': ['-generated_on']},
        ),
        migrations.AddField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_status_changed', 'Task Status Changed'), ('task_completed', 'Task Completed'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('project_completed', 'Project Completed'), ('team_joined', 'Team Joined'), ('team_left', 'Team Left'), ('deadline_approaching', 'Deadline Approaching'), ('mention', 'Mention'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectreport',
            name='report_type',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='projects_no_user_id_c143d9_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read'], name='projects_no_user_id_06976d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['action_type'], name='projects_no_action__ef911c_idx'),
        ),
    ]
