# Generated by Django 5.1.4 on 2024-12-23 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_user_email_alter_file_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'team')},
        ),
    ]
