# Generated by Django 5.1.4 on 2024-12-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_team_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
    ]
