# Generated by Django 5.1.4 on 2024-12-31 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_teammember_created_by_user_is_project_manager_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
