# Generated by Django 5.1.4 on 2024-12-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_user_email_user_projects_us_usernam_6d3597_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['user', 'team'], name='projects_te_user_id_112b1b_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['role'], name='projects_te_role_55333c_idx'),
        ),
    ]
