# Generated by Django 5.1.4 on 2025-01-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_team_options_team_avatar_team_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(help_text='Upload task-related files (max 10MB)', upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(help_text='Name of the uploaded file', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Provide detailed information about the task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Enter a clear, descriptive title for the task', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('project', 'title'), name='unique_task_title_in_project'),
        ),
    ]
