# Generated by Django 5.1.4 on 2025-01-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_user_is_project_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='teammember',
            name='unique_team_member',
        ),
        migrations.RemoveIndex(
            model_name='teammember',
            name='projects_te_user_id_112b1b_idx',
        ),
        migrations.RemoveIndex(
            model_name='teammember',
            name='projects_te_role_55333c_idx',
        ),
    ]
